version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: todoapp_g77m_user
      POSTGRES_PASSWORD: MJovArDsluu5fbHq1ww6SzLD2wADkCAq
      POSTGRES_DB: todoapp_g77m
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
