services:
  php-app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:

